jobs:
    include:
        -   language: python
            python:
                - "3.8"
                - "3.8-dev"  # 3.8 development branch

            install:
                - pip install -r server/requirements.txt

            script:
                - python server/test.py -v

        -   language: node_js
            node_js:
                - "node"
            script:
                - "cd spa-spreadsheet"
                - "yarn"
                - "yarn lint"
#                - "yarn test"  - no tests yet

deploy:
    provider: elasticbeanstalk
    access_key_id:
        secure: $AWS_ACCESS_KEY_ID
    secret_access_key:
        secure: $AWS_ACCESS_KEY_SECRET
    region: $AWS_REGION
    app: $AWS_EB_APPLICATION
    env: $AWS_EB_ENVIRONMENT
    bucket_name: $AWS_EB_S3_BUCKET